#!/bin/sh

export USER="username"
export HOME="/home/username"

groups="$(id -Gn "$USER" | tr ' ' ':')"
svdir="$HOME/.service"

exec chpst -b "runsvdir-$USER" -u "$USER:$groups" -n 5 runsvdir "$svdir"
