alias cal='cal --monday'
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -hl --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias nnn='nnn -e'
alias ping='ping -c 5'
alias tmuxn='tmux new-session -s'
alias tmuxa='tmux attach-session'
alias tmuxl='tmux list-sessions'
