alias cal='cal --monday'
alias ls='ls --color=auto'
alias l.='ls -d .* --color=auto'
alias ll='ls -hl --color=auto'
alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias nnn='nnn -e'
alias ping='ping -c 5'
# tmux
alias tmuxn='tmux new-session -s'
alias tmuxa='tmux attach-session'
alias tmuxl='tmux list-sessions'
# git
alias gita='git add'
alias gitb='git branch'
alias gitbd='git branch --delete'
alias gitba='git branch --all'
alias gitbl='git branch --list'
alias gitc='git commit'
alias gitcn='git commit --amend --no-edit'
alias gitca='git commit --amend'
alias gitcl='git clone --recursive'
alias gitds='git diff --staged'
alias gitdh1='git diff HEAD~1 HEAD'
alias gitlg='git log --graph --all --pretty=format:"%C(magenta)%h %C(white) %an  %ar%C(auto)  %D%n%s%n"'
alias gitm='git merge'
alias gitu='git push'
alias gitl='git pull'
alias gitr1='git reset --mixed HEAD~1'
alias gitst='git status --short'
alias gitw='git switch'
alias gitwc='git switch -c'
