#!/bin/sh
exec 2>&1

dae validate -c /etc/dae/config.dae || exit 1

install -d -m 700 -o _dae -g _dae /var/lib/dae

if ! mountpoint -q /sys/fs/bpf; then
	mkdir -p /sys/fs/bpf
	mount -t bpf bpf /sys/fs/bpf
fi

exec dae run \
	--disable-pidfile \
	--disable-timestamp \
	--logfile /var/lib/dae/dae.log \
	-c /etc/dae/config.dae
