STOP_CHARGE_THRESH_BAT0=1

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0
CPU_BOOST_ON_SAV=0

WIFI_PWR_ON_BAT=on

DEVICES_TO_DISABLE_ON_BAT_NOT_IN_USE="bluetooth"

DISK_DEVICES="nvme0n1"

PCIE_ASPM_ON_AC=performance
PCIE_ASPM_ON_BAT=default

CPU_SCALING_GOVERNOR_ON_AC=performance
CPU_SCALING_MIN_FREQ_ON_AC=1400000
CPU_SCALING_MAX_FREQ_ON_AC=2100000

CPU_SCALING_GOVERNOR_ON_BAT=schedutil
CPU_SCALING_MIN_FREQ_ON_BAT=1400000
CPU_SCALING_MAX_FREQ_ON_BAT=1700000

CPU_SCALING_GOVERNOR_ON_SAV=powersave
CPU_SCALING_MAX_FREQ_ON_SAV=1400000
CPU_SCALING_MIN_FREQ_ON_SAV=1400000
