#
# Download Efficiency
#
max-concurrent-downloads=5
max-connection-per-server=16
min-split-size=10M
split=16
continue=true

#
# Speed and Error Handling
#
max-tries=6
retry-wait=5
timeout=20

#
# Session Persistence
#
input-file=${HOME}/.config/aria2/aria2.session
save-session=${HOME}/.config/aria2/aria2.session
save-session-interval=60

#
# Disk and Memory Optimization
#
dir=${HOME}/Downloads
disk-cache=128M
enable-mmap=true
file-allocation=falloc

#
# BitTorrent (BT/Magnet) Settings
#
bt-enable-lpd=true
enable-dht6=true
dht-file-path=${HOME}/.config/aria2/dht.dat
dht-file-path6=${HOME}/.config/aria2/dht6.dat
dht-entry-point=dht.transmissionbt.com:6881
dht-entry-point6=dht.transmissionbt.com:6881
bt-save-metadata=true
seed-time=240

#
# Loglevel
#
log-level=warn
