#!/bin/sh
set -eu

# close window
riverctl map normal Super Q close
# exit river
riverctl map normal Super+Shift E exit
# focus-view
riverctl map normal Super H focus-view left
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right
riverctl map normal Super J focus-view down
# swap window
riverctl map normal Super+Alt H swap left
riverctl map normal Super+Alt J swap down
riverctl map normal Super+Alt K swap up
riverctl map normal Super+Alt L swap right
# focus-output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma  focus-output previous
# move window
riverctl map -repeat normal Super Left move left 50
riverctl map -repeat normal Super Down move down 50
riverctl map -repeat normal Super Up move up 50
riverctl map -repeat normal Super Right move right 50
# snap window
riverctl map normal Super+Alt Left snap left
riverctl map normal Super+Alt Down snap down
riverctl map normal Super+Alt Up snap up
riverctl map normal Super+Alt Right snap right
# resize window
riverctl map -repeat normal Control+Shift H resize horizontal -50
riverctl map -repeat normal Control+Shift K resize vertical 50
riverctl map -repeat normal Control+Shift J resize vertical -50
riverctl map -repeat normal Control+Shift L resize horizontal 50
# fullscreen
riverctl map normal Super F toggle-fullscreen
# float
riverctl map normal Super Space toggle-float
# stack
riverctl map normal Super G zoom
# send-to-output
riverctl map normal Super+Shift Comma send-to-output next
riverctl map normal Super+Shift Period send-to-output previous
# send-to-previous-tags
riverctl map normal Super+Shift P send-to-previous-tags
# tags
for i in $(seq 1 9)
do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Control+Shift $i toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
# scratchpad
scratch_tag=$((1 << 20 ))
riverctl map normal Super D toggle-focused-tags ${scratch_tag}
riverctl map normal Super+Shift D set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
# sticky
all_tags=$(((1 << 32) - 1))
sticky_tag=$((1 << 31))
all_but_sticky_tag=$(( $all_tags ^ $sticky_tag ))
riverctl map normal Super S toggle-view-tags $sticky_tag
riverctl spawn-tagmask ${all_but_sticky_tag}
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $(($sticky_tag + $tags))
done
# main-location
riverctl map normal Super+Control H  send-layout-cmd rivertile "main-location left"
riverctl map normal Super+Control L  send-layout-cmd rivertile "main-location right"
riverctl map normal Super+Control K  send-layout-cmd rivertile "main-location top"
riverctl map normal Super+Control J  send-layout-cmd rivertile "main-location bottom"
# main-ratio
riverctl map normal Super+Shift H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal Super+Shift L send-layout-cmd rivertile "main-ratio +0.05"
# main-count
riverctl map normal Super+Shift K send-layout-cmd rivertile "main-count +1"
riverctl map normal Super+Shift J send-layout-cmd rivertile "main-count -1"
# fuzzel
riverctl map normal Super A spawn "fuzzel"
# firefox
riverctl map normal Super B spawn "firefox-wayland"
# foot
riverctl map normal Super T spawn "footclient"
# swaylock
riverctl map normal Super Escape spawn "swaylock"
# zzz
riverctl map normal Super Z spawn "doas zzz -z"
riverctl map normal Super+Shift Z spawn "notify-send 'Sleep!!!' && doas zzz -Z"
# volume
riverctl map -repeat normal Super+Control Bracketleft spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-" 
riverctl map -repeat normal Super+Control Bracketright spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+" 
riverctl map normal Super+Control Equal spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
riverctl map -repeat normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
riverctl map -repeat normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
# light
riverctl map -repeat normal None XF86MonBrightnessUp  spawn "brightnessctl set +10%"
riverctl map -repeat normal None XF86MonBrightnessDown spawn "brightnessctl set 10%-"
riverctl map -repeat normal Super+Control Apostrophe spawn "brightnessctl set +10%"
riverctl map -repeat normal Super+Control Semicolon spawn "brightnessctl set 10%-"
riverctl map normal Super+Control Slash spawn "brightnessctl set 5%"
# player 
riverctl map normal	None XF86AudioPrev spawn "playerctl previous"
riverctl map normal	None XF86AudioPlay  spawn "playerctl play-pause "
riverctl map normal	None XF86AudioNext spawn "playerctl next"
riverctl map normal	Control+Alt Left spawn "playerctl previous"
riverctl map normal	Control+Alt Up spawn "playerctl play-pause "
riverctl map normal	Control+Alt Down spawn "playerctl play-pause "
riverctl map normal	Control+Alt Right spawn "playerctl next"
# screenshot
riverctl map normal	None XF86SelectiveScreenshot spawn "screenshot.sh"
riverctl map normal	Alt XF86SelectiveScreenshot spawn "screenshot.sh window"
riverctl map normal	Control XF86SelectiveScreenshot spawn "screenshot.sh full"
# screencap
riverctl map normal	Super Backslash spawn "screencast.sh start"
riverctl map normal	Super+Shift Backslash spawn "screencast.sh stop"
