#!/bin/sh

# close window
riverctl map normal Super Q close
# exit river
riverctl map normal Super+Shift E exit
# focus-view
riverctl map normal Super H focus-view left
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right
riverctl map normal Super J focus-view down
# swap window
riverctl map normal Super+Alt H swap left
riverctl map normal Super+Alt J swap down
riverctl map normal Super+Alt K swap up
riverctl map normal Super+Alt L swap right
# focus-output
riverctl map normal Super Period focus-output next
riverctl map normal Super Comma  focus-output previous
# move window
riverctl map -repeat normal Super Left move left 50
riverctl map -repeat normal Super Down move down 50
riverctl map -repeat normal Super Up move up 50
riverctl map -repeat normal Super Right move right 50
# snap window
riverctl map normal Super+Alt Left snap left
riverctl map normal Super+Alt Down snap down
riverctl map normal Super+Alt Up snap up
riverctl map normal Super+Alt Right snap right
# resize window
riverctl map -repeat normal Control+Shift H resize horizontal -50
riverctl map -repeat normal Control+Shift K resize vertical 50
riverctl map -repeat normal Control+Shift J resize vertical -50
riverctl map -repeat normal Control+Shift L resize horizontal 50
# fullscreen
riverctl map normal Super F toggle-fullscreen
# float
riverctl map normal Super Space toggle-float
# stack
riverctl map normal Super G zoom
# send-to-output
riverctl map normal Super+Shift Comma send-to-output next
riverctl map normal Super+Shift Period send-to-output previous
# send-to-previous-tags
riverctl map normal Super+Shift P send-to-previous-tags
# tags
for i in $(seq 1 9)
do
	tags=$((1 << ($i - 1)))
	riverctl map normal Super $i set-focused-tags $tags
	riverctl map normal Super+Shift $i set-view-tags $tags
	riverctl map normal Super+Control $i toggle-focused-tags $tags
	riverctl map normal Super+Control+Shift $i toggle-view-tags $tags
done
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags
# scratchpad
scratch_tag=$((1 << 20 ))
riverctl map normal Super D toggle-focused-tags ${scratch_tag}
riverctl map normal Super+Shift D set-view-tags ${scratch_tag}
all_but_scratch_tag=$(( ((1 << 32) - 1) ^ $scratch_tag ))
riverctl spawn-tagmask ${all_but_scratch_tag}
# sticky
all_tags=$(((1 << 32) - 1))
sticky_tag=$((1 << 31))
all_but_sticky_tag=$(( $all_tags ^ $sticky_tag ))
riverctl map normal Super S toggle-view-tags $sticky_tag
riverctl spawn-tagmask ${all_but_sticky_tag}
for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal Super $i set-focused-tags $(($sticky_tag + $tags))
done
