#!/bin/sh

. $HOME/.config/river/auto
. $HOME/.config/river/misc
. $HOME/.config/river/modes
. $HOME/.config/river/rules
. $HOME/.config/river/layout
. $HOME/.config/river/inputs
. $HOME/.config/river/bindings
