#!/bin/sh
set -eu

# tile
riverctl default-layout rivertile
riverctl spawn "rivertile -view-padding 3 -outer-padding 3 -main-location right -main-count 1 -main-ratio 0.7"
# attach-mode
riverctl default-attach-mode below
