#!/bin/sh

FIFO="/tmp/sandbar"
[ -e "$FIFO" ] && rm -f "$FIFO"
mkfifo "$FIFO"

while cat "$FIFO"; do :; done | sandbar \
	-no-layout \
	-vertical-padding 2 \
	-font "Hack:style=Blod:size=14" \
	-active-fg-color "#000000" \
	-active-bg-color "#a4e378" \
	-inactive-fg-color "#ebdbb2" \
	-inactive-bg-color "#000000" \
	-urgent-fg-color "#000000" \
	-urgent-bg-color "#cc241d" \
	-title-fg-color "#000000" \
	-title-bg-color "#a4e378"
	
	
