# Use four public NTP servers from the pool.ntp.org project.
pool cn.pool.ntp.org iburst minpoll 10 maxpoll 13

# Record the rate at which the system clock gains/losses time.
driftfile /var/lib/chrony/drift

# Allow the system clock to be stepped in the first three updates
# if its offset is larger than 1 second.
makestep 1.0 3

# Enable kernel synchronization of the real-time clock (RTC).
rtcsync

minsources 3

server ntp.aliyun.com iburst minpoll 10 maxpoll 13
server ntp.tencent.com iburst minpoll 10 maxpoll 13
server time.apple.com iburst minpoll 10 maxpoll 13
