table inet default {
	include "nftables/defines.nft"
	include "nftables/limits.nft"
	include "nftables/sets.nft"
	
	chain input_ipv4 {
		include "nftables/input-ipv4.nft"
	}
	chain input_ipv6 {
		include "nftables/input-ipv6.nft"
	}

	chain input {
		type filter hook input priority filter; policy drop;
		iif "lo" accept
		ct state vmap { invalid : drop, established : accept, related : accept }
		include "nftables/input-common.nft"
		iifname $INET_DEV meta nfproto vmap { ipv4 : jump input_ipv4, ipv6 : jump input_ipv6 }
	}
 	chain forward {
		type filter hook forward priority filter; policy accept;
	}
	chain output {
		type filter hook output priority filter; policy accept;
	}
	include "nftables/prerouting.nft"
}
