#!/bin/sh
set -euf

FPATH="$1"
FNAME=$(basename "$1")
EDITOR=${EDITOR:-vi}
PAGER="${PAGER:-less -R}"

ext=""
case "$FNAME" in
    *.*) ext="${FNAME##*.}" ;;
esac
ext=$(printf "%s" "$ext" | tr '[:upper:]' '[:lower:]')

handle_video() {
	if type mpv &> /dev/null; then
		nohup mpv "${FPATH}" &> /dev/null &
	else
		return
	fi
	exit 0
}

handle_pdf() {
	if type zathura &> /dev/null; then
		nohup zathura "${FPATH}" &> /dev/null &
	else
		return
	fi
	exit 0
}

handle_photo() {
	if type imv &> /dev/null; then
		nohup imv "${FPATH}" &> /dev/null &
	else
		return
	fi
	exit 0
}

handle_ext() {
	case "${ext}" in
		pdf)
			handle_pdf ;;
		mp4|mkv|mp3|wav|flac|flv)
			handle_video ;;
		log|rs|py|sh|ini|toml|conf|json|jsonc|txt|sql|md)
			"${EDITOR}" "${FPATH}"
			exit 0;;
		jpg|jpeg|png|gif|bmp|webp|svg)
			handle_photo ;;
		*)
			exit 0;;
	esac
}

handle_ext
exit 1
