kernel_cmdline+=" psi=1 "

kernel_cmdline+=" iommu.strict=0 "
kernel_cmdline+=" swiotlb=131072 "
kernel_cmdline+=" transparent_hugepage=always "

kernel_cmdline+=" rd.luks.allow-discards "
kernel_cmdline+=" rd.luks.uuid=2dfd21cb-7751-4ebb-a0f9-096dfba2995d "

kernel_cmdline+=" rd.lvm.vg=vg2 "

kernel_cmdline+=" rootfstype=xfs "
kernel_cmdline+=" rootflags=rw,relatime "
kernel_cmdline+=" root=UUID=a3678ec0-4eae-44cd-a74d-1a67608ca6d3 "

kernel_cmdline+=" resume=UUID=a3678ec0-4eae-44cd-a74d-1a67608ca6d3 "
kernel_cmdline+=" resume_offset=227326 "

kernel_cmdline+=" apparmor=1 "
kernel_cmdline+=" security=apparmor "
