#!/bin/sh
exec 2>&1

exec setpriv \
	--reuid=_sing_box --regid=_sing_box --clear-groups \
	--inh-caps=-all,+net_admin,+net_raw,+net_bind_service,+sys_ptrace,+dac_read_search \
	--ambient-caps=-all,+net_admin,+net_raw,+net_bind_service,+sys_ptrace,+dac_read_search \
	--bounding-set=-all,+net_admin,+net_raw,+net_bind_service,+sys_ptrace,+dac_read_search \
	--no-new-privs -- \
	/usr/bin/sing-box -D /var/lib/sing-box -C /etc/sing-box run
