#!/bin/sh
set -eu

cpu() {
	cpu="CPU:$(top -bn1 | grep "%Cpu(s)" | awk '{ printf "%.0f%%\n",$2 + $4 }')"
}

memory() {
	memory="MEM:$(free -m | awk '/Mem:/ {printf "%.0f%%\n", $3 / $2 * 100}')"
}

disk_root() {
	disk_root="DISK@/:$(df / | grep -Eo "[0-9]{1,}%")"
}

disk_home() {
	disk_home="DISK@/home:$(df /home | grep -Eo "[0-9]{1,}%")"
}

datetime() {
	datetime="$(date "+%a %b %d %I:%M %P")"
}

bat() {
	read -r bat_status </sys/class/power_supply/BAT1/status
	read -r bat_capacity </sys/class/power_supply/BAT1/capacity
	bat="BAT:$bat_status($bat_capacity%)"
}

light() {
	_current=$(brightnessctl get)
	_max=$(brightnessctl max)
	light="LIGHT:$(((_current * 100) / _max))%"
}

vol() {
	_vol=$(wpctl get-volume @DEFAULT_SINK@ 2>/dev/null)
	case "$_vol" in
		*MUTED*) vol='VOL:MUTED' ;;
		*) vol="VOL:$(printf '%s' "$_vol" | awk '{printf "%.0f%%\n", $2*100}')" ;;
	esac
}

wifi() {
	wifi="WIFI:$(cat /sys/class/net/wl*/operstate 2>/dev/null | awk '{print toupper(substr($0,1,1)) tolower(substr($0,2))}')"
}

temp() {
	read -r raw_temp </sys/class/thermal/thermal_zone0/temp
	temp="TEMP:$(($raw_temp / 1000))°C"
}

display() {
	printf 'all status [%s %s %s %s %s] [%s] [%s] [%s] [%s] [%s]\n' \
        "$cpu" "$temp" "$memory" "$disk_root" "$disk_home" "$light" "$vol" "$wifi" "$bat" "$datetime" > "$FIFO_FILE"
}

DATA_DIR="/tmp/sandbar-$(id -u)"
PID_FILE="$DATA_DIR/pid"
printf "%s" "$$" > "$PID_FILE"

FIFO_FILE="$DATA_DIR/fifo"
[ -e "$FIFO_FILE" ] || mkfifo "$FIFO_FILE"

trap '{ rm -f "$FIFO_FILE" "$PID_FILE"; exit 0; }' INT TERM

sec=0
while :; do
	sleep 1 &
	wait && {
		[ $((sec % 60)) -eq 0 ] && bat
		[ $((sec % 60)) -eq 0 ] && disk_home
		[ $((sec % 60)) -eq 0 ] && disk_root
		[ $((sec % 60)) -eq 0 ] && datetime
		[ $((sec % 30)) -eq 0 ] && memory
		[ $((sec % 5)) -eq 0 ] && cpu
		[ $((sec % 5)) -eq 0 ] && temp
		[ $((sec % 5)) -eq 0 ] && vol
		[ $((sec % 5)) -eq 0 ] && wifi
		[ $((sec % 5)) -eq 0 ] && light
		[ $((sec % 5)) -eq 0 ] && display
		sec=$((sec + 1))
	}
done
