server:
    interface: 127.0.0.1
    access-control: 127.0.0.0/8 allow
    
    msg-cache-size: 128m
    rrset-cache-size: 256m
    prefetch: yes
    serve-expired: yes
    serve-expired-ttl: 86400
    serve-expired-client-timeout: 1800

    qname-minimisation: yes
    hide-identity: yes
    hide-version: yes
    minimal-responses: yes
    private-address: 10.0.0.0/8
    private-address: 172.16.0.0/12
    private-address: 192.168.0.0/16

    module-config: "validator iterator"
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
    tls-cert-bundle: "/etc/ssl/certs/ca-certificates.crt"

remote-control:
    control-enable: yes
    control-interface: 127.0.0.1

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-addr: 1.1.1.1@853#cloudflare-dns.com
    forward-addr: 1.0.0.1@853#cloudflare-dns.com
    forward-addr: 8.8.8.8@853#dns.google
    forward-addr: 8.8.4.4@853#dns.google
