# opacity
rules: ({
    match = "class_g = 'Alacritty' && focused";
    opacity = 0.8;
},{
    match = "class_g = 'Alacritty' && !focused";
    opacity = 1.0;
},{
    match = "class_g = 'Firefox'";
    opacity = 0.8;
})

# blur
blur: {
    method = "dual_kawase";
    strength = 4;
    background = true;
}
