#!/bin/sh
# @author rendong
# @since 2025-07-17

. $HOME/.config/river/auto
. $HOME/.config/river/layout
. $HOME/.config/river/bindings
. $HOME/.config/river/modes
. $HOME/.config/river/rules

# fuzzel
riverctl map normal Super A spawn "fuzzel"
# firefox
riverctl map normal Super B spawn "firefox-wayland"
# foot
riverctl map normal Super T spawn "footclient"
# swaylock
riverctl map normal Super Escape spawn "swaylock"
# zzz
riverctl map normal Super Z spawn "notify-send 'Sleep!!!' && doas zzz -Z"
# keyboard
riverctl set-repeat 50 400
riverctl keyboard-layout-file "$HOME/.config/xkb/keyboard.xkb"  
# touchpad
for i in $(riverctl list-inputs | grep -i touchpad); do
    riverctl input "$i" tap enabled
    riverctl input "$i" disable-while-typing enabled
    riverctl input "$i" click-method button-areas
    riverctl input "$i" scroll-factor 1.25 
done
# mouse
for i in $(riverctl list-inputs | grep -i mouse); do
    riverctl input "$i" accel-profile flat
    riverctl input "$i" natural-scroll enabled
    riverctl input "$i" scroll-factor 1.25 
done
# volume
riverctl map normal None XF86AudioLowerVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%-" 
riverctl map normal None XF86AudioRaiseVolume spawn "wpctl set-volume @DEFAULT_AUDIO_SINK@ 10%+"
riverctl map normal None XF86AudioMute spawn "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
# light
riverctl map normal None XF86MonBrightnessUp  spawn "brightnessctl set +10%"
riverctl map normal None XF86MonBrightnessDown spawn "brightnessctl set 10%-"
# color 
riverctl background-color 0x0A0A12 
riverctl border-color-focused 0x00FFC8 
riverctl border-color-unfocused 0x3A4D44
# cursor
riverctl focus-follows-cursor disabled
riverctl xcursor-theme adwaita 16
riverctl hide-cursor timeout 5000
riverctl hide-cursor when-typing enabled
riverctl set-cursor-warp on-output-change
