#! /bin/sh

: "${XDG_CONFIG_HOME:=$HOME/.config}"

. "$XDG_CONFIG_HOME/bspwm/inputs"
. "$XDG_CONFIG_HOME/bspwm/auto"
. "$XDG_CONFIG_HOME/bspwm/rules"

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width          4
bspc config window_gap            4
bspc config top_padding           32
bspc config bottom_padding        0
bspc config left_padding          0
bspc config right_padding         0

bspc config normal_border_color   "#8DB6CD"
bspc config active_border_color   "#E5E0E0"
bspc config focused_border_color  "#66CD00"
bspc config presel_feedback_color "#97FFFF"

bspc config split_ratio           0.50
bspc config automatic_scheme      longest_side
bspc config focus_follows_pointer true
bspc config focus_follows_monitor true
bspc config focus_follows_focus   false
bspc config removal_adjustment    true

#
# monocle mode
#

# Remove borders when in monocle (single window) mode
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config paddingless_monocle   false
bspc config single_monocle        false

bspc wm -o
