[colors]
cursor = { text = "#2F4F4F", cursor = "#FFD700" }
selection = { text = "#2F4F4F", background = "#FFD700" }

[colors.primary]
background = "#2F4F4F"
foreground = "#FFFAFA"

[colors.normal]
black = "#1A2626"
red = "#CD3700"
green = "#66CD00"
yellow = "#CDAD00"
blue = "#8DB6CD"
magenta = "#CD2990"
cyan = "#79CDCD"
white = "#E5E0E0"

[colors.bright]
black = "#5F8787"
red = "#FF4500"
green = "#7FFF00"
yellow = "#FFD700"
blue = "#B0E2FF"
magenta = "#FF34B3"
cyan = "#97FFFF"
white = "#FFFAFA"
